language: python
python:
- '2.7'
script:
- cd pyArchery
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password:
    secure: IHPnYdTlIj4hyJm8ZjMgkJthLYAO1DjthYnCAl9P2mHPjdQB0V2K55lkiO2H+WDmjkqzq1G9g5fOwsYFmaCZsAILP3KaolsQ3zSyDgePTFpLKdhjhqPDJUTbgdb07srTZKYW19f217zyC5/O9/4T5TKosaH4P08+kAN8rfi8ECHKcw2S4NBn4aBNqJ7s+3Rd6kqSa85i0U6UroG4rsOE6xybt71Eyqubr9xPNeZ/3GuR6R59rE3+05RpVKksi9sJMG3Ts8ZD8Jxchc5cAukVhSYCoencURqOpB+f1zoGJ9F3WN9BXKlYSmpYHy4QspAuL6aOc7j2HMr7XSp5Ri2mif3WsPC64Uv09VU7mHWwKya+B0mPp4w5JJiq5U7umkXkvXUVFiFRQR56EiP1HtnkplTaeOqw2NPb37vVuNAoJcUwp87TIvFMKMg4p75XTWy/tPZ6B/ZsVJWLRu8s0JokEnfeowimhKHjTdQ867TEGGE8S0Ztno8S2VXOoCuS0BjnO/QajAOq8P8BsAqcJOO8ZjO1dU9dGrJqZ7qXOt+BQImYO9mS3odvOTkT2mideGJoVR3H41oyk7OW8jOAAWKCf9c/li+fXAmKTBa7EjWslIMBRKvUhXui0R9AhuO0DQRWNC/WTM2D4SnRiFsh6V1ANGd5WpLOsAIPkt3CV6ruI5g=
  on:
    distributions: sdist bdist_wheel
    repo: archerysec/archerysec-python-package
    branch: deploy
