language: python
python:
- '2.7'
script:
- python pyArchery/setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password:
    secure: op+YjzzS+6rRyQUBI8mm6JqsmyFqp4G/DJ01C2CK6JrLlsqFS6JkJxZwn41OeZt5r4EMdmVOHkrlW6LGPnZMJbM7AiIn82dVXMIq4DiZmOD+Qh+ZTt8J4CdnQUDEVxIDusZV/DE0EyNVfI3dBCjfm99UZvqR0h/lq75jmEQJURycBcvZsF8kcYjHvmOCs9Eig5mDMCZeNaIQwhADcJ5hG6yD4nUtfK/b6VqbdkoEONNWTAMVqtNdlAsn1k4evfYD2sxvkocCEKhAe2ywe2I/gDhDQB7T8j9tIx+8I/6W1x2U2V1o9h0fX3HnGoFlwEmqNScFqK7v8CdpAbak9n+Tn3AQwNM3h5ceKRIEyYqnsjgWdZwpVG6c0EyD+WFq85+85QZUIn3YJzaCMiSbBQbL24RXJK7Be82nu7e3K+Jv8vacJXP7lxhGOQJJAG7/KkMlSJxL8YiP2Y3Nf79CRAZK33rq33AYgLWctaBDYXqw2f1zOXdNhVYrY58yFdBxMU+tQYLGY7fAAqB01xWBkHJE9GfVreAqhtbe9bRXiUnlgHf2WAWhTAY2eBQw/XhlsMKDOu8p6Kwrbtv0pNfHUmQ59ZYnAN4KpjSFer9Z3wz7IAx3gQOLfrsrG/bGd1nVCxfDEs/Hcgm2b/ZlKqjG5nj4jzdMx1qGva/+Akw58aCpMzU=
  on:
    distributions: sdist bdist_wheel
    repo: archerysec/archerysec-python-package
