language: python
python:
- '2.7'
script:
- cd pyArchery
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password:
    secure: M9kIgP0yFA28uD0tUO2J7k7BKajYt4EjQBtiaqGfJviozQamkUh2VHRHN6qGTd0cI6mJd1i+9mOGFg3PP9QlIy0iRnhp8BDDLMzY1JAIpUiq7e5gAiTOZr8+2jjDSNEqGiBvUHqA4abBjf58BCLDa6PexE6GSLwFzghXO9SaGv4iL/EyXejZDqMObiuWR0HolIUt9cApIsUzJcRuIsyBTWD8FHtWWpxRs9sgn25fBoTs2C6nHeDLDbWBxTnWO2TYNI+XnuKRpwTYuaJnft9Y2Edhdas8MWS0z8sybl1lZnM4bGTj8cfAISOk9+9/IjdzUKu6XcKo4RRRqNBX0XVhRhxXPYPCh1U65gdiGVje1hTuKB8RIGXDxL2I5lvQC12eqCaYrOmBRa6hxiQjkO+/SBlVf58iRDRHoG4uDdzHAx/9SjS3n3P/OgkIsq31kKurhIsct5F0mKzMcHIPyFCu5AdWEUJ7q4tsdWLs1vCgTfEtjIIEcQdN+QT0X/bSzFPgtT1DVLSYe7MnF/A0UBfuofoixhDeYYLXerAlySpRVMUrpI44CORZwWbBSlLvbV5aBNQvu3H3xvJfH8Acp1FPGmZVJx9nLaz+4aNjy4eLB13ibcZNMpsKVM+wvEk8Oob4L9i3qWepbx1ad/hRMbdvqq7a+IozBhf+YMX+E8D7r3k=
  on:
    distributions: sdist bdist_wheel
    repo: archerysec/archerysec-python-package
    branch: deploy
