language: python
python:
- '2.7'
script:
- cd pyArchery
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password:
    secure: 4x+pyXvRFyN5SPJ6Lm2NUsbCRirzl6jsuKYvGV1oquGh45dMtQ+iai1A7P24OIhRgH3XUd/0fmmL3uFNW/XM8if03y3KkpIv6eq7ifEp5DKcRfpAgUlJa6L8Vo7gzv718LJj+rgc0X7JjDI8/RXqaH6DoiMdTmpOEDX+6eOfeMPByVyOasUQ56gIJfnZm3fS+dSgaVBhwEBI9fzRl6mmq8ax4XDDvsxzKqXwaFJRoDFM6IG4hh0sRItusk7ILs4wNySBcNf42ecX1ZREkBkZRqHdNC4pHydIdZys83jrjjSnged1OV4MAlyRdU3meDvOTgKzpXCX/qFo3JqfSmSeMmQK6ghqL1juEq6qX+FH85W7OBjOW8qlI5rzR5qcLiaEuAtCiVmlfp/Uv7AHv4BHoTIDvacJE3SRD8iKPMNIN9L3f2MKgOxVUcl4iib/H3eMQGWZDtfITWPetjjqD9QlOQH2tIqP+TM4BlbxShMiSLq070QOpPcCAr9wDHUs0JSNZzLt0qfTixv2lGMUxUWakgfHW7n5zRGexAG21x3JVcnvTcCM95kesjb7DlcsqijOKBB0CPMBXwZmQVMzvEoFNpaRvLx2U9UJ7GpJQP7SGBjPBljNZEDE8pAmV06HblV8qVlOQXWYJ+6RgsPXe8HdjMhlGG9cwBU/47CryWdcqP4=
  on:
    distributions: sdist bdist_wheel
    repo: archerysec/archerysec-python-package
    branch: deploy
